(test
 (name lexer_tests)
 (libraries OneF))

(executable
 (name test_lexer)
 (modules test_lexer)
 (public_name test_lexer)
 (libraries OneF)
 (instrumentation
  (backend bisect_ppx)))

(executable
 (name test_interpreter)
 (modules test_interpreter)
 (public_name test_interpreter)
 (libraries OneF)
 (instrumentation
  (backend bisect_ppx)))

(executable
 (name test_eval)
 (modules test_eval)
 (public_name test_eval)
 (libraries OneF)
 (instrumentation
  (backend bisect_ppx)))

(executable
 (name test_menhir_eval)
 (modules test_menhir_eval)
 (public_name test_menhir_eval)
 (libraries OneF))

(executable
 (name bench_menhir)
 (modules bench_menhir)
 (public_name bench_menhir)
 (libraries OneF unix))

(executable
 (name check_paths)
 (modules check_paths)
 (public_name check_paths)
 (libraries OneF))

(executable
  (name bench_angstrom)
  (modules bench_angstrom)
  (public_name bench_angstrom)
  (libraries OneF unix))

(executable
  (name bench_ocamlyacc)
  (modules bench_ocamlyacc)
  (public_name bench_ocamlyacc)
  (libraries OneF unix))

(executable
  (name bench_all)
  (modules bench_all)
  (public_name bench_all)
  (libraries OneF unix angstrom))

(executable
  (name test_ocamlyacc)
  (modules test_ocamlyacc)
  (public_name test_ocamlyacc)
  (libraries OneF))

(cram
 (deps "./test_lexer.exe" "./test_interpreter.exe" "./test_eval.exe" "./test_menhir_eval.exe"))
