name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3.x

      - name: Install dependencies
        run: opam install . --deps-only --with-test -y

      - name: Build
        run: opam exec -- dune build

      - name: Run tests
        run: opam exec -- dune runtest
